name: OpenMM-Torch-Build-Wheels

env:
  GIT_REVISION: 'master'
  VERSION_SUFFIX: ''

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    name: "${{ matrix.name }} ${{ matrix.python-version}}"
    strategy:
      matrix:
        python-version: ["3.10"]
        include:
          - name: Linux x86
            os: ubuntu-latest
            requirements: linux
            cuda-version: "12-3"
            cuda-arch: "x86_64"
            hip-version: "6"

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build-env
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: bash

      - name: "Install dependencies with pip"
        shell: bash -l {0}
        run: pip install -v -r devtools/requirements/${{ matrix.requirements }}.txt

      - name: "Install dependencies with yum"
        run: |
          yum -y install zip opencl-headers ocl-icd

      - name: "Install CUDA"
        run: |
          dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/${{ matrix.cuda-arch }}/cuda-rhel8.repo
          dnf -y install cuda-compiler-${{ matrix.cuda-version }}.${{ matrix.cuda-arch }} \
                         cuda-libraries-${{ matrix.cuda-version }}.${{ matrix.cuda-arch }} \
                         cuda-libraries-devel-${{ matrix.cuda-version }}.${{ matrix.cuda-arch }}

      - name: "Install HIP"
        run: |
          yum install -y epel-release
          yum install -y https://repo.radeon.com/amdgpu-install/6.2.2/el/8.10/amdgpu-install-6.2.60202-1.el8.noarch.rpm
          yum install -y rocm-device-libs hip-devel hip-runtime-amd hipcc

      - name: "Check out OpenMM-Torch source code"
        run: |
          git clone https://github.com/openmm/openmm-torch.git
          cd openmm-torch
          git checkout $GIT_REVISION

      - name: "Configure build with CMake"
        shell: bash -l {0}
        run: |
          cd openmm-torch
          mkdir build
          cd build
          export SITE_PACKAGES=$(python -c 'import site; print(site.getsitepackages()[0]))
          echo $SITE_PACKAGES
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=${SITE_PACKAGES}/OpenMM.libs \
            -DCMAKE_CXX_COMPILER=/opt/rocm/bin/amdclang++ \
            -DOPENMM_DIR=${SITE_PACKAGES}/OpenMM.libs \
            -DTorch_DIR=${SITE_PACKAGES}/torch/share/cmake/Torch \
            -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0' \
            -DNN_BUILD_OPENCL_LIB=ON \
            -DNN_BUILD_CUDA_LIB=ON \
            -DNN_BUILD_HIP_LIB=ON \
            -DOPENCL_INCLUDE_DIR=/usr/include/CL \
            -DOPENCL_LIBRARY=/usr/lib64/libOpenCL.so.1

      - name: "Build OpenMM-Torch"
        shell: bash -l {0}
        run: |
          cd openmm-torch/build
          make -j4 install
          make -j4 PythonInstall

      - name: "Build wheel"
        shell: bash -l {0}
        run: |
          cd openmm-torch/build
          export CUDA_VERSION=$(cut -d '-' -f1 <<< ${{ matrix.cuda-version }})
          make PythonBdistWheel
          export LD_LIBRARY_PATH=${HOME}/openmm-install/lib
          cd python/dist
          export SITE_PACKAGES=$(python -c 'import site; print(site.getsitepackages()[0]))
          python $GITHUB_WORKSPACE/devtools/scripts/add_plugins_and_headers.py "${SITE_PACKAGES}/OpenMM.libs" "!CUDA" "!HIP"
          auditwheel repair -w fixed -L ".libs/lib" --plat manylinux_2_28_x86_64 *.whl \
            --exclude libOpenMM.so \
            --exclude libOpenMMCUDA.so \
            --exclude libOpenMMHIP.so \
            --exclude libOpenMMOpenCL.so \
            --exclude libOpenCL.so.1 \
            --exclude libcuda.so.1 \
            --exclude libcufft.so.11 \
            --exclude libcufft.so.10 \
            --exclude libnvrtc.so.11.2 \
            --exclude libnvrtc.so.12 \
            --exclude libhiprtc.so.6 \
            --exclude libamdhip64.so.6

#      - name: "Build CUDA wheel"
#        shell: bash -l {0}
#        run: |
#          cd $GITHUB_WORKSPACE/devtools/cuda
#          export OPENMM_VERSION=$(echo $(grep "OPENMM_VERSION:" $GITHUB_WORKSPACE/openmm/build/CMakeCache.txt) | cut -d '=' -f2)$VERSION_SUFFIX
#          export CUDA_VERSION=$(cut -d '-' -f1 <<< ${{ matrix.cuda-version }})
#          python setup.py bdist_wheel
#          cd dist
#          python $GITHUB_WORKSPACE/devtools/scripts/add_plugins_and_headers.py "${HOME}/openmm-install" "CUDA"
#          mv *.whl $GITHUB_WORKSPACE/openmm/build/python/dist/fixed
#
#      - name: "Build HIP wheel"
#        shell: bash -l {0}
#        run: |
#          cd $GITHUB_WORKSPACE/devtools/hip
#          export OPENMM_VERSION=$(echo $(grep "OPENMM_VERSION:" $GITHUB_WORKSPACE/openmm/build/CMakeCache.txt) | cut -d '=' -f2)$VERSION_SUFFIX
#          export HIP_VERSION=${{ matrix.hip-version }}
#          python setup.py bdist_wheel
#          cd dist
#          python $GITHUB_WORKSPACE/devtools/scripts/add_plugins_and_headers.py "${HOME}/openmm-install" "HIP"
#          mv *.whl $GITHUB_WORKSPACE/openmm/build/python/dist/fixed
#
#      - name: "Rename wheels"
#        shell: bash -l {0}
#        run: |
#          python $GITHUB_WORKSPACE/devtools/scripts/rename_wheels.py $GITHUB_WORKSPACE/openmm/build/python/dist/fixed
#
#      - name: "Test the wheel"
#        shell: bash -l {0}
#        run: |
#          set -x
#          python -m venv "${HOME}/test_env"
#          source "${HOME}/test_env/bin/activate"
#          cd openmm-torch/build/python/dist
#          export CUDA_VERSION=$(cut -d '-' -f1 <<< ${{ matrix.cuda-version }})
#          pip install --pre -f fixed openmm[cuda${CUDA_VERSION},hip${{ matrix.hip-version }}]
#          python -m openmm.testInstallation
#          python -c "import openmm as mm; print(mm.version.openmm_library_path)"
#          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"
#
#      - name: "Upload the wheel"
#        uses: actions/upload-artifact@v4
#        with:
#          name: openmm-torch-wheel-linux-${{matrix.python-version}}
#          path: openmm-torch/build/python/dist/fixed
#          retention-days: 10
